---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tetris
  description: Tetris application deployed through the Azure IDP
  annotations:
    github.com/project-slug: akashcoder02/azure-devops-aks-demo
    argocd/app-name: tetris
    argocd/app-namespace: argocd
    argocd/instance-name: primary
spec:
  type: service
  lifecycle: production
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tic-tac-toe
  description: Tic-Tac-Toe application deployed through the Azure IDP
  annotations:
    github.com/project-slug: akashcoder02/azure-devops-aks-demo
    argocd/app-name: tic-tac-toe
    argocd/app-namespace: argocd
    argocd/instance-name: primary
spec:
  type: service
  lifecycle: production
  owner: platform-team
